baseURL = "/"
languageCode = "en-us"
title = "ATLA API Docs"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'ATLA is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = 'https://imgs.search.brave.com/5f7pGQwxqBnGay9-icNFx8gQnMTMqDjTWGhm3DPepgA/rs:fit:498:249:1/g:ce/aHR0cHM6Ly9tZWRp/YTEudGVub3IuY29t/L2ltYWdlcy8wNzk3/NmNmZjAzMDI5ZTQw/ZGM0YzMzYzVmNmVm/ODNkYy90ZW5vci5n/aWY_aXRlbWlkPTY1/MjA0NjE.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Avatar: The Last Airbender API. Built with Go and Hugo."
    meta_og_title = "Avatar: The Last Airbender API"
    meta_og_type = "website"
    meta_og_url = "https://atla-api.fly.dev/"
    meta_og_description = "Avatar: The Last Airbender API. Built with Go and Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@the_brianb"
    meta_twitter_creator = "@the_brianb"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
